### ISSUE TITLE
解在姓氏时读音错误了

### ISSUE THREAD

**Issue by Jooyer** [heimuheimu/util-pinyin#2]
大佬:
       你好, 我在使用本库获取 '解狐" 的读音时,发现 "解" 此时返回了 "jie" ,应该是 "xiè"
读音：[xiè], 出自姬姓．以邑名为氏．掘《万姓统谱》所载．周成王弟叔虞之子良．含采于解邑（在今山西省解县)，后人以邑为解氏
     望大佬修复下此bug!

**Comment by heimuheimu** [comment]
util-pinyin 库是通过词库来识别多音字的，目前的词库没有收录人名，你可以自行修改，来维护一份自己的词库。

词库文件地址：/com/heimuheimu/util/pinyin/dictionary/multi_pinyin_mapping.txt（在 resources 目录下）

格式说明：

> 与,yu3
> yu2,与人书一,与人无争,与世无竞,与人方便
> yu4,与会,参与,与闻,实与有力,事与心违

第一行，第一个字符为多音字，后面跟着的拼音为该字符的默认发音（没有匹配中自定义词组时使用的发音）
后面几行为多音字发音以及关联的词组，如果有词组匹配中，将会使用该行的发音。
注意：分隔符为英文 ","。

以你的问题为例：
在 2157 行末尾加入 “解狐” 的词语即可

**Comment by Jooyer** [comment]
多谢大佬指点,我试试!
